export const GET_MESSAGES_SUCCESS = '@@messages/GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILURE = '@@messages/GET_MESSAGES_FAILURE'
export const SEND_MESSAGE_SUCCESS = '@@messages/SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = '@@messages/SEND_MESSAGE_FAILURE'
